def getSvHeader():
    return ["startChrIndex",
            "endChrIndex",
            "startPos",
            "endPos",
            "eventScore",
            "eventType",
            "clonality",
            "source1",
            "source2",
            "overhang1",
            "overhang2",
            "startCytobandIndex",
            "endCytobandIndex",
            "gene1",
            "cancerGene1",
            "nearestGeneUpstream1",
            "nearestGeneUpstreamDistance1",
            "nearestCancerGeneUpstream1",
            "nearestCancerGeneUpstreamDistance1",
            "nearestGeneDownstream1",
            "nearestGeneDownstreamDistance1",
            "nearestCancerGeneDownstream1",
            "nearestCancerGeneDownstreamDistance1",
            "gene2",
            "cancerGene2",
            "nearestGeneUpstream2",
            "nearestGeneUpstreamDistance2",
            "nearestCancerGeneUpstream2",
            "nearestCancerGeneUpstreamDistance2",
            "nearestGeneDownstream2",
            "nearestGeneDownstreamDistance2",
            "nearestCancerGeneDownstream2",
            "nearestCancerGeneDownstreamDistance2",
            "dbSuperEntries1",
            "dbSuperEntries2",
            "startFragileSiteIndex",
            "endFragileSiteIndex",
            "maxRecurrence",
            "maxIntraPatientRecurrence",
            "preRemapStartChrIndex",
            "preRemapEndChrIndex",
            "preRemapStartPos",
            "preRemapEndPos",
            "directHits",
            "tadIndicesOffset0",
            "tadIndicesOffset1",
            "tadIndicesOffset2",
            "tadIndicesOffset3",
            "donor"]


def getIndelHeader():
    return ["chrIndex",
            "pos",
            "ref",
            "alt",
            "gene",
            "smallVarType",
            "tadIndicesOffset0",
            "tadIndicesOffset1",
            "tadIndicesOffset2",
            "tadIndicesOffset3",
            "toskip",
            "donor"]
def getSnvHeader():
    return ["chrIndex",
            "pos",
            "ref",
            "alt",
            "gene",
            "smallVarType",
            "toskip",
            "index",
            "donor"]